DONT MERGE ME - a draft of first pass moving user events to template
Casa/node-ts-lambda-template pull request #7
Opened 2022-04-13 15:54 UTC by logansease

much work to do, and obviously will move this to its own repo and not merge this to the template, but I wanted to get a PR of the diff of the code i'm working with so far as a starting place for convo

2022-04-13 16:01 UTC, logansease commented on src/controllers/userEvents.controller.ts
> +const hubspotClient = new hs({ apiKey: process.env.HUBSPOT_API_KEY });
TODO- move this to config instead of env

2022-04-13 16:02 UTC, logansease commented on src/controllers/userEvents.controller.ts
> +        const dbClient = databaseService.getConnection();
TODO move the db queries and inserts out to a userEvents service

2022-04-13 16:02 UTC, logansease commented on src/controllers/userEvents.controller.ts
> +        const insertStatement = 'INSERT INTO "userEvents"(id, "userId", "eventName", "eventDetail", "eventMetadata", "loggedBy") VALUES($1, $2, $3, $4, $5, $6) RETURNING *';
TODO- should I add a UserEvent model with sequelize?

2022-04-13 16:03 UTC, logansease commented on src/lambda.ts
> +  // TODO: clean up db connection
how can i clean up the db connection without having to do it in each controller method?

2022-04-13 16:03 UTC, logansease commented on src/providers/index.ts
> +    container.registerService(
I feel like there should be a more elegant way to inject controllers without having to register them

2022-04-13 16:04 UTC, logansease commented on src/services/database.service.ts
> +        const countUserEventsQueryStatement =
TODO- move migrations to one per file

2022-04-13 16:05 UTC, logansease commented on src/services/database.service.ts
> +        const countUserEventsQueryStatement =
and... is there a better way to do migrations instead of manually in code checking to see if the are run and running. Downside is there is no way to rollback

2022-04-13 16:06 UTC, logansease commented on src/controllers/userEvents.controller.ts
> +    async sendToHubspot(body) {
TODO- don't pass the body in here. Give this a strong type

2022-04-13 16:06 UTC, logansease commented on src/controllers/userEvents.controller.ts
> +        if (queryParams && queryParams.userId) {
TODO- we probably want to require this parameter

2022-04-13 16:07 UTC, logansease commented on src/routes/index.ts
> +  `${BASE_ROUTE}/application/status`, container.applicationStatusController.index,
TODO: Is there a way to incorporate an ID into a route??

2022-04-13 18:33 UTC, armins88 commented on src/controllers/userEvents.controller.ts
> +const uuid = require('uuid');
es6 imports are supported

2022-04-13 18:33 UTC, armins88 commented on src/controllers/userEvents.controller.ts
> +const hubspotClient = new hs({ apiKey: process.env.HUBSPOT_API_KEY });
Also pull for SSM instead of env vars

2022-04-13 18:40 UTC, armins88 requested changes

2022-04-13 18:40 UTC, armins88 commented on src/controllers/userEvents.controller.ts
> +    async index(dbClient, queryParams) {
controller methods would take res and req objects similar to how express works 
https://github.com/Casa/node-ts-lambda-template/blob/develop/src/controllers/applicationStatus.controller.ts#L7

2022-04-13 18:40 UTC, armins88 commented on src/controllers/userEvents.controller.ts
> +        const insertStatement = 'INSERT INTO "userEvents"(id, "userId", "eventName", "eventDetail", "eventMetadata", "loggedBy") VALUES($1, $2, $3, $4, $5, $6) RETURNING *';
Having a model object and typescript would make the most sense

2022-04-13 18:40 UTC, armins88 commented on src/providers/index.ts
> +    container.registerService(
Yeah I was battling with this one. The controller should be treated as services. I changed this paradigm in #9

2022-04-13 18:40 UTC, armins88 commented on src/routes/index.ts
> +  `${BASE_ROUTE}/application/status`, container.applicationStatusController.index,
https://www.npmjs.com/package/lambda-api

2022-04-13 18:40 UTC, armins88 commented on src/routes/index.ts
> +api.get(
If the lambda function is a single resource API (pricing API, user events) I think it makes more sense to keep them in one file.

2022-04-13 18:40 UTC, armins88 commented on src/services/database.service.ts
> +        const countUserEventsQueryStatement =
Sequlize migrations would be the best way to do this. If we are taking the time to refactor user events service I think it could be nice to use an ORM

2022-04-13 18:43 UTC, armins88 commented on src/lambda.ts
> +  // TODO: clean up db connection
I think the controller should manage its own resources. The lambda is initiated when a request comes in and torn down after its done serving that function. If the controller is the only consumer of the database service then it makes sense that it also disposes it


```ts
res.json(paylod)
...
await db.dispose()
```

2022-04-13 19:19 UTC, logansease commented on src/lambda.ts
> +  // TODO: clean up db connection
since pretty much every controller method of a project that uses a db connection will need one, that would mean we 
have to add boiler plate code to every controller method to sourround it in a  try catch, release after returning- and if the controller is calling services for its DB calls like I plan to do, it has to pass those connections into each service method. 

What will probably happen is an implementer won't do all those steps properly every time and we'll end up with a bunch of leaked db connections. It would be better to find a way to make this more global. 
Could we initialize the container in the lambda.ts file instead and pass it through to the routes file instead of waiting to set that up?

2022-04-13 19:22 UTC, logansease commented on src/routes/index.ts
> +api.get(
yeah, that's true- but services usually grow in scope over time -- that will probably result in them not being in separate files when new resources get added if we don't encourage good practices from the beginning.

2022-04-13 19:23 UTC, logansease commented on src/services/database.service.ts
> +        const countUserEventsQueryStatement =
yeah- prob won't tackle that now, but its good to know that it's possible. 
I do think there would be a lot of value in having some of that postgres and sequelize stuff in the template project. It is much easier to remove it when not needed then to go and add it, and make sure it is done in a good scalable way.

2022-04-13 20:04 UTC, armins88 commented on src/lambda.ts
> +  // TODO: clean up db connection
>  it has to pass those connections into each service method.
It should not be passed in as a function param, instead, the services will have an already initialized db service injected.

2022-04-13 20:05 UTC, armins88 commented on src/lambda.ts
> +  // TODO: clean up db connection
Also on second thought, a more 'global' way to handle disposing the db connection properly is to incorporate it into the service using the disposable interface 
https://github.com/microsoft/tsyringe#disposable-instances

2022-04-13 20:06 UTC, armins88 commented on src/lambda.ts
> +  // TODO: clean up db connection
That was we only have to call dispose in one place `container.dispose();` 

Probably in route.ts

2022-04-13 20:07 UTC, armins88 commented on src/services/database.service.ts
> +        const countUserEventsQueryStatement =
MVP?

2022-04-13 20:08 UTC, logansease commented on src/lambda.ts
> +  // TODO: clean up db connection
I found this in the lambda-api docs:

```

The API has a built-in clean up method called 'finally()' that will execute after all middleware and routes have been completed, but before execution is complete. This can be used to close database connections or to perform other clean up functions. A clean up function can be defined using the finally method and requires a function with two parameters for the REQUEST and the RESPONSE as its only argument. For example:

api.finally((req, res) => {
  // close unneeded database connections and perform clean up
});
```

2022-04-13 20:22 UTC, logansease commented on src/services/database.service.ts
> +        const countUserEventsQueryStatement =
nope- and its something that I'm sort of tackling anyways for this UserEvents port

2022-04-13 20:24 UTC, logansease commented on src/routes/index.ts
> +api.get(
So lambda-api has the ability to use separate routes files, but it doesn't seem to be compatible with the whole 'Container' concept bc the container is initialized and contained in the main routes file. 
Do you have any ideas how this can work?

```
// handler.js
const api = require('lambda-api')();

api.register(require('./routes/v1/products'));

module.exports.handler = (event, context, callback) => {
  api.run(event, context, callback);
};

// routes/v1/products.js
module.exports = (api, opts) => {
  api.get('/product', handler_v1);
};
```

2022-04-13 21:27 UTC, logansease commented on src/lambda.ts
> +  // TODO: clean up db connection
Implemented that in newest commit

2022-04-14 12:27 UTC, armins88 commented on src/routes/index.ts
> +api.get(
Not sure I totally understand. Cant, you inject the dependencies from the container? There is no need to pass the container object around.

2022-04-14 12:38 UTC, armins88 commented on src/services/userEvents.service.ts
> +export interface UserEventsServiceInjector {
Injector implies that this is the thing injecting. Interfaces actually don't pertain to DI or the functionality of the container. A better name might just be `UserEvents`.

2022-04-14 12:39 UTC, armins88 commented on src/services/userEvents.service.ts
> +export interface UserEventsServiceInjector {
This is one of the pros of using IResourceName. We don't have to debate the philosophy of the classes that are implementing the interface. I think this is especially important since we are **not** OOP paradigm

2022-04-14 12:42 UTC, armins88 commented on src/controllers/userEvents.controller.ts
> +    constructor(userEventsService: userEventsService) {
Nit: This could be a one liner
`constructor(@inject('UserEventsService') private userEventsService: IUserEventsService) {}`

2022-04-14 12:42 UTC, armins88 commented on src/controllers/userEvents.controller.ts
> +            UserEventsService.sentToHubspot(eventBody)
Do we want to log something in case this fails?

2022-04-14 12:45 UTC, armins88 commented on src/routes/index.ts
> +  await container.databaseService.release()
I think the api finally method is great but I would highly encourage the use of disposables. 
https://github.com/microsoft/tsyringe#disposable-instances

i.e: await container.dispose();

2022-04-18 20:15 UTC, logansease commented on src/routes/index.ts
> +api.get(
resolved by instanciating the controller in the route file

2022-04-18 20:18 UTC, logansease commented on src/services/userEvents.service.ts
> +export interface UserEventsServiceInjector {
I initially thought that the reason we were defining this interface was for injection - but I believe I am now understanding it is for creating mock services during injection, correct?
In my other PR I changed this slightly to 'UserInterface' vs 'IUser' - I def prefer that because it is explicit rather than using an acronym that is supposed to be implicitly understood by the reader

2022-04-18 20:18 UTC, logansease commented on src/controllers/userEvents.controller.ts
> +    constructor(userEventsService: userEventsService) {
agreed

2022-04-18 20:19 UTC, logansease commented on src/routes/index.ts
> +  await container.databaseService.release()
oh interesting- okay, let's sync on that in my other user-events repo and I'll see if I can get that to work instead

2022-04-18 20:20 UTC, logansease commented
Closed and move to https://github.com/Casa/user-events-from-template @armins88

2022-04-18 20:20 UTC, closed without merging