Doc updates
Casa/node-ts-lambda-template pull request #8
Opened 2022-04-13 18:08 UTC by browep

2022-04-13 18:19 UTC, logansease submitted a review, later dismissed

2022-04-13 18:24 UTC, armins88 requested changes

2022-04-13 18:24 UTC, armins88 commented on package.json
> +    "deploy-dev": "aws lambda update-function-code --function-name casa-dev-${npm_package_name} --zip-file fileb://dist/lambda.zip",
because we have to mock deploy this template in the near future this will break our CI/CD. Can you please revert this portion. After the mock deploy I will add this change

2022-04-13 18:46 UTC, armins88 commented on package.json
> +    "deploy-dev": "aws lambda update-function-code --function-name casa-dev-${npm_package_name} --zip-file fileb://dist/lambda.zip",
Oops didnt realize that ${npm_package} gets replaced by the package name

2022-04-14 16:44 UTC, armins88 approved these changes

2022-04-14 16:45 UTC, merged